local config = require("task-manager.config")

describe("config", function()
  before_each(function()
    config.setup()
  end)

  describe("defaults", function()
    it("sets feature token", function()
      assert.equals("## Feature {feature}: {name}", config.options.tokens.feature)
    end)

    it("sets task token", function()
      assert.equals("- [ ] {feature}.{task} {name}", config.options.tokens.task)
    end)

    it("sets subtask token", function()
      assert.equals("- [ ] {feature}.{task}.{subtask} {name}", config.options.tokens.subtask)
    end)

    it("enables keymaps", function()
      assert.is_true(config.options.keymaps.enabled)
    end)

    it("sets spacing defaults to 0", function()
      assert.equals(0, config.options.spacing.after_feature)
      assert.equals(0, config.options.spacing.after_task)
      assert.equals(0, config.options.spacing.after_subtask)
    end)
  end)

  describe("deep merge", function()
    it("overrides a single token without affecting others", function()
      config.setup({ tokens = { feature = "# FEAT {feature}: {name}" } })
      assert.equals("# FEAT {feature}: {name}", config.options.tokens.feature)
      assert.equals("- [ ] {feature}.{task} {name}", config.options.tokens.task)
      assert.equals("- [ ] {feature}.{task}.{subtask} {name}", config.options.tokens.subtask)
    end)

    it("overrides keymaps.enabled", function()
      config.setup({ keymaps = { enabled = false } })
      assert.is_false(config.options.keymaps.enabled)
    end)

    it("does not mutate defaults", function()
      config.setup({ tokens = { feature = "CHANGED" } })
      assert.equals("## Feature {feature}: {name}", config.defaults.tokens.feature)
    end)

    it("overrides spacing options", function()
      config.setup({ spacing = { after_feature = 1, after_task = 2 } })
      assert.equals(1, config.options.spacing.after_feature)
      assert.equals(2, config.options.spacing.after_task)
      assert.equals(0, config.options.spacing.after_subtask)
    end)

    it("calling setup() with no args restores defaults", function()
      config.setup({ keymaps = { enabled = false } })
      config.setup()
      assert.is_true(config.options.keymaps.enabled)
    end)
  end)
end)
