local config = require("task-manager.config")

describe("config", function()
  before_each(function()
    config.setup()
  end)

  describe("defaults", function()
    it("sets feature token", function()
      assert.equals("## Feature {feature}: {name}", config.options.tokens.feature)
    end)

    it("sets task token", function()
      assert.equals("- [ ] {feature}.{task} {name}", config.options.tokens.task)
    end)

    it("sets subtask token", function()
      assert.equals("- [ ] {feature}.{task}.{subtask} {name}", config.options.tokens.subtask)
    end)

    it("enables keymaps", function()
      assert.is_true(config.options.keymaps.enabled)
    end)

    it("sets spacing defaults to 0", function()
      assert.equals(0, config.options.spacing.after_feature)
      assert.equals(0, config.options.spacing.after_task)
      assert.equals(0, config.options.spacing.after_subtask)
      assert.equals(0, config.options.spacing.before_feature)
      assert.equals(0, config.options.spacing.before_task)
      assert.equals(0, config.options.spacing.before_subtask)
    end)
  end)

  describe("deep merge", function()
    it("overrides a single token without affecting others", function()
      config.setup({ tokens = { feature = "# FEAT {feature}: {name}" } })
      assert.equals("# FEAT {feature}: {name}", config.options.tokens.feature)
      assert.equals("- [ ] {feature}.{task} {name}", config.options.tokens.task)
      assert.equals("- [ ] {feature}.{task}.{subtask} {name}", config.options.tokens.subtask)
    end)

    it("overrides keymaps.enabled", function()
      config.setup({ keymaps = { enabled = false } })
      assert.is_false(config.options.keymaps.enabled)
    end)

    it("does not mutate defaults", function()
      config.setup({ tokens = { feature = "CHANGED" } })
      assert.equals("## Feature {feature}: {name}", config.defaults.tokens.feature)
    end)

    it("overrides spacing options", function()
      config.setup({ spacing = { after_feature = 1, after_task = 2 } })
      assert.equals(1, config.options.spacing.after_feature)
      assert.equals(2, config.options.spacing.after_task)
      assert.equals(0, config.options.spacing.after_subtask)
    end)

    it("overrides before spacing options", function()
      config.setup({ spacing = { before_feature = 1, before_task = 2, before_subtask = 3 } })
      assert.equals(1, config.options.spacing.before_feature)
      assert.equals(2, config.options.spacing.before_task)
      assert.equals(3, config.options.spacing.before_subtask)
      assert.equals(0, config.options.spacing.after_feature)
    end)

    it("calling setup() with no args restores defaults", function()
      config.setup({ keymaps = { enabled = false } })
      config.setup()
      assert.is_true(config.options.keymaps.enabled)
    end)
  end)

  describe("kicked", function()
    it("defaults to 'kicked'", function()
      assert.equals("kicked", config.options.kicked)
    end)

    it("can be overridden", function()
      config.setup({ kicked = "archive" })
      assert.equals("archive", config.options.kicked)
    end)

    it("does not mutate defaults when overridden", function()
      config.setup({ kicked = "other" })
      assert.equals("kicked", config.defaults.kicked)
    end)
  end)

  describe("spec", function()
    it("defaults to 'plan.md'", function()
      assert.equals("plan.md", config.options.spec)
    end)

    it("can be overridden with a file path", function()
      config.setup({ spec = "docs/spec.md" })
      assert.equals("docs/spec.md", config.options.spec)
    end)

    it("can be overridden with a directory", function()
      config.setup({ spec = "docs/" })
      assert.equals("docs/", config.options.spec)
    end)

    it("does not mutate defaults when overridden", function()
      config.setup({ spec = "other.md" })
      assert.equals("plan.md", config.defaults.spec)
    end)
  end)
end)
